#!/bin/bash
#准备工作，node1 node2 node3 各分三个区
#实现ceph集群的自动配置

#ceph环境配置
source ./ceph_envir_ready

NODE_IPS=`awk '/node/{print $1}' data_ceph.conf`
client_ip=`awk '/client/{print $1}' data_ceph.conf`


########################################################
#创建ceph集群配置，安装节点软件包，初始化mon服务
########################################################
create_ceph_config (){

yum -y install ceph-deploy
[ ! -d /root/ceph-cluster ] &&  mkdir /root/ceph-cluster

#自动生成配置文件
ceph-deploy new node1 node2 node3
#给所有节点安装软件包
ceph-deploy install node1 node2 node3
#初始化所有节点的mon服务
ceph-deploy mon create-initial
ceph-deploy --overwrite-conf mon create node1 node2 node3

}
########################################################
#创建OSD  磁盘分区
########################################################
create_osd (){

cat > /etc/udev/rules.d/70-vdb.rules << EOF
ENV{DEVNAME}=="/dev/vdb1",OWNER="ceph",GROUP="ceph"
ENV{DEVNAME}=="/dev/vdb2",OWNER="ceph",GROUP="ceph"
EOF

for IP in $NODE_IPS
do
expect << EOF
spawn ssh $IP	
expect "#"   { send "[ -e /dev/vdb2 ] || parted /dev/vdb mklabel gpt\r" }
expect "#"   { send "[ -e /dev/vdb2 ] || parted /dev/vdb mkpart primary 1M 50%\r" }
expect "#"   { send "[ -e /dev/vdb2 ] || parted /dev/vdb mkpart primary 50% 100%\r" }
expect "#"   { send "chown ceph.ceph /dev/vdb1\r" }
expect "#"   { send "chown ceph.ceph /dev/vdb2\r" }
expect "#"   { send "exit\r" }

expect eof
EOF

scp /etc/udev/rules.d/70-vdb.rules $IP:/etc/udev/rules.d/

done


#格式化磁盘vdc和vdd
ceph-deploy disk zap node1:vdc node1:vdd 
ceph-deploy disk zap node2:vdc node2:vdd 
ceph-deploy disk zap node3:vdc node3:vdd 

#创建OSD存储空间
ceph-deploy osd create node1:vdc:/dev/vdb1 node1:vdd:/dev/vdb2
ceph-deploy osd create node2:vdc:/dev/vdb1 node2:vdd:/dev/vdb2
ceph-deploy osd create node3:vdc:/dev/vdb1 node3:vdd:/dev/vdb2

}

#客户端自动连接
client_krbd (){

expect << EOF
spawn ssh -o StrictHostKeyChecking=no $client_ip 
expect "password:" { send "1\r" }
expect "#" { send "rpm -q ceph-common || yum -y install ceph-common\r" }
expect "#" { send "scp 192.168.4.11:/etc/ceph/ceph.* /etc/ceph/\r" }
expect "password:" { send "1\r" }
expect "#" { send "rbd map image\r" }
expect "#" { send "exit\r" }
expect eof
EOF

}

map_config (){

#创建镜像
rbd list | grep -q demo-image || rbd create demo-image --image-feature  layering --size 10G
rbd list | grep -q image || rbd create rbd/image --image-feature  layering --size 10G

#扩大容量
rbd resize --size 15G image

}



########################################################
#部署ceph
########################################################
ceph_deploy (){

cd /root/ceph-cluster

create_ceph_config
create_osd
map_config
client_krbd

}


ceph_deploy
