#!/bin/bash

#实现无密码远程一群主机
#使用前提：将所有要远程的ip，定义为变量IPS,用法：ssh_copy_id_to_all $PASSWORD  
#$PASSWORD为所有要远程的主机的一样的密码

#密钥配对
auto_ssh_copy_id() {

rpm -q expect ||  yum -y install expect

    expect -c "set timeout -1;
        spawn ssh-copy-id $1;
        expect {
            *(yes/no)* {send -- yes\r;exp_continue;}
            *assword:* {send -- $2\r;exp_continue;}
            eof        {exit 0;}
        }";
}


#实现无密码远程
ssh_copy_id_to_all() {

#如果公钥不存在，就生成公钥
[ ! -f /root/.ssh/id_rsa ] && ssh-keygen -f /root/.ssh/id_rsa -N ''

for IP in $IPS
do
    auto_ssh_copy_id $IP $1  &> /dev/null
done
echo "密钥配对成功！！！"

}



